# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20', '1.21']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Vet
      run: go vet ./...

    - name: Tidy
      run: go mod tidy && git diff --exit-code

    - name: Mod
      run: go mod download

    - name: Mod Verify
      run: go mod verify

    - name: Generate
      run: go generate ./... && git diff --exit-code

    - name: Test
      run: go test -v -count=1 -race -shuffle=on -cover ./...
      env:
        APITOOLKIT_KEY: ${{ secrets.APITOOLKIT_KEY }}


  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        go: ['1.20', '1.21']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - run: go build -o /dev/null ./...
